In [ ]:
import sys
import ast
import numpy as np
import pandas as pd
from datetime import datetime, timedelta

import csv
csv.field_size_limit(sys.maxsize)

def date_parser(x):
    ''' Parses date string to datetime '''
    try:
        return datetime.strptime(x, '%Y-%m-%d')
    except ValueError:
        print(x)
        return np.nan

def get_name_list(x):
    ''' Extracts list of names form a string representation of a list '''
    ret = list(map(lambda x: x['name'], ast.literal_eval(x)))
    if not ret:
        ret = np.nan
    return ret

def cast_gender(x):
    ''' Casts gender string to integer '''
    if x == 0:
        return 'Not specified'
    elif x == 1:
        return 'Female'
    elif x == 2:
        return 'Male'

def get_name_gender_list(x):
    ''' Creates list of (name, gender) tuples - relevant for "cast" column '''
    ret = list(map(lambda x: (x['id'], x['name'], cast_gender(x['gender'])), ast.literal_eval(x)))
    if not ret:
        ret = np.nan
    return ret

def get_name_gender_job_list(x):
    ''' Creates list of (name, gender, job) triples - relevant for "crew" column '''
    ret = list(map(lambda x: (x['id'], x['name'], cast_gender(x['gender']), x['job']), ast.literal_eval(x)))
    if not ret:
        ret = np.nan
    return ret

# For casting column types in "Movies" table.
movie_column_types = {
    'budget': float,
    'genres': str,
    'homepage': str,
    'id': int,
    'keywords': str,
    'original_language': str,
    'original_title': str,
    'overview': str,
    'popularity': float,
    'production_companies': str,
    'production_countries': str,
    'revenue': float,
    'runtime': float,
    'spoken_languages': str,
    'status': str,
    'tagline': str,
    'title': str,
    'vote_average': float,
    'vote_count': float
}

# For casting column types in "Credits" table.
credits_column_types = {
    'movie_id': int,
    'title': str,
    'cast': str,
    'crew': str
}

# For final table.
relevant_columns = [
    'budget',
    'genres',
    'keywords',
    'original_language',
    'original_title',
    'overview',
    'popularity',
    'production_companies',
    'production_countries',
    'release_year',
    'revenue',
    'vote_average',
    'vote_count',
    'cast',
    'crew'
]

# The crawled data has 7 partitions: [1-100k), [100k-200k), ..., [600k-700k).
# We iterate over the partitions and wrangle them accordingly.
for i in range(1,8):
    print(i)
    
    # Load the "Movies" table from the current partition.
    df_movies = pd.read_csv(f'data/tmdb_100k_movies_{i}.csv',
                            engine='python',
                            dtype=movie_column_types,
                            parse_dates=['release_date'],
                            date_parser=date_parser)
    # Drop movies that do not have a value in the release date column.
    df_movies = df_movies[~df_movies.release_date.isna()]

    # Load the "Credits" table.
    df_credits = pd.read_csv(f'data/tmdb_100k_credits_{i}.csv',
                             engine='python',
                             dtype=credits_column_types)
    # Rename "movie_id" column for easier join.
    df_credits.rename(columns={'movie_id': 'id'}, inplace=True)
    
    # *** Wrangle "Movies" table ***
    
    # Copy "Movies" table so we don't mess the original data.
    df_movies_cp = df_movies.copy()

    # Set "id" column as index so we can join both tables on it later.
    df_movies_cp.set_index('id', inplace=True)

    # Preprocess the relevant clumns by using the utility functions defined above.
    df_movies_cp['genres'] = df_movies_cp['genres'].apply(get_name_list)
    df_movies_cp['keywords'] = df_movies_cp['keywords'].apply(get_name_list)
    df_movies_cp['production_companies'] = df_movies_cp['production_companies'].apply(get_name_list)
    df_movies_cp['production_countries'] = df_movies_cp['production_countries'].apply(get_name_list)
    df_movies_cp['spoken_languages'] = df_movies_cp['spoken_languages'].apply(get_name_list)
    
    # Extract the year form the "release_year" column.
    # We are going to groupy by the year only.
    df_movies_cp['release_year'] = df_movies_cp.release_date.apply(lambda x: int(x.year))
    df_movies_cp.drop(columns=['release_date'], inplace=True)

    print('Done wrangling "Movies" table')

    # *** Wrangle "Credits" table ***

    # Copy "Credits" table so we don't mess the original data.
    df_credits_cp = df_credits.copy()

    # Set "id" column as index so we can join both tables on it later.
    df_credits_cp.set_index('id', inplace=True)

    # Preprocess the relevant clumns by using the utility functions defined above.
    df_credits_cp['cast'] = df_credits_cp['cast'].apply(get_name_gender_list)
    df_credits_cp['crew'] = df_credits_cp['crew'].apply(get_name_gender_job_list)
    
    # Drop "title" column.
    # We already have a "original_title" column.
    df_credits_cp.drop(columns=['title'], inplace=True)

    print('Done wrangling "Credits" table')
    
    # Joining both tables.
    # It will do so using the index.
    df = df_movies_cp.join(df_credits_cp)

    print('Joined both tables')

    # Replace nan values in "budget" and "revenue" columns with 0.
    df.budget.replace(0, np.nan, inplace=True)
    df.revenue.replace(0, np.nan, inplace=True)

    # Project relevant columns
    df = df[relevant_columns]

    print('Projected relevant columns')
    
    # Store the wrangled 100k dataset.
    df.to_csv(f'data/tmdb_100k_{i}.csv')

# Now, load all the wrangled partitions and concatenate them in a big table.
df = pd.concat([pd.read_csv(f'data/tmdb_100k_{i}.csv', engine='python') for i in range(1,8)])

# Store the 500k table.
df.to_csv('data/tmdb_500k.csv', index=False)

# Note, many of the movies are for adults.
# We additionally crawled TMDB for that indicator variable.

## Filtering adult movies

In [ ]:
df = pd.read_csv('data/tmdb_500k.csv', engine='python', dtype=dtype)
df_adult = pd.read_csv('data/is_adult.csv', engine='python', dtype={'id': int, 'adult': bool})
df = df.merge(df_adult, on='id')

# saving the final dataset
df[df.adult == False][list(dtype.keys())].to_csv('data/tmdb_100k.csv', index=False)